server:
  port: 4040

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: Ahmed1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
